hw4 : main.o WordNetwork.o List.o Node.o
	g++ main.o WordNetwork.o List.o Node.o -o hw4

WordNetwork.o : WordNetwork.cpp
	g++ -c WordNetwork.cpp

List.o : List.cpp
	g++ -c List.cpp

Node.o : Node.cpp
	g++ -c Node.cpp

main.o : main.cpp
	g++ -c main.cpp